services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: affiliate_tracker
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  back-end: # Changed from "app" to "back-end"
    container_name: affiliate_tracker_back_end
    image: affiliate_tracker_app_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Map container port 3000 to host port 3001
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run start:dev"
    depends_on:
      mysql:
        condition: service_healthy

  # front-end:
  #   container_name: affiliate_tracker_front_end
  #   image: affiliate_tracker_front_end_image
  #   build:
  #     context: ../front-end
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" # Map container port 3000 to host port 3000
  #   volumes:
  #     - ../front-end:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - NEXT_PUBLIC_API_END_URL=http://localhost:3001
  #   command: sh -c "npm run dev"
  #   depends_on:
  #     - back-end

volumes:
  mysql_data:
