DROP DATABASE IF EXISTS ${MYSQL_DATABASE};
DROP DATABASE IF EXISTS ${MYSQL_DATABASE_SHADOW};

CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_SHADOW};

GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_SHADOW}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
