CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE_SHADOW};

GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE_SHADOW}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
